rocq-community/coqeal

- refinements/bareiss.v
- theory/binetcauchy.v
- theory/dvdring.v
- theory/minor.v
- theory/ssrcomplements.v
- v0.1/Qinfra.v
- v0.1/Zinfra.v
- v0.1/bareiss.v
- v0.1/bareiss_dvdring.v
- v0.1/bareiss_pseudo.v
- v0.1/binetcauchy.v
- v0.1/cdvdring.v
- v0.1/cseqpoly.v
- v0.1/cseqpolydvd.v
- v0.1/cssralg.v
- v0.1/dvdring.v
- v0.1/karatsuba.v
- v0.1/minor.v
- v0.1/polydvd.v
- v0.1/rank.v
- v0.1/seqmatrix.v
- v0.1/ssrcomplements.v
- v0.2/bareiss.v
- v0.2/rank.v
- v0.2/toomcook.v
This is a minor bugfix.
I split it in two different commit in case you wouldn't want to change the old-releases folders {v0.1,v0.2}.
(Also maybe you'd want to make paramcoq-dev the default branch in place of master?)
Kind regards.
> Fix vernacular command

- refinements/_CoqProject
- refinements/binnat.v
- refinements/multipoly.v
- theory/ssrcomplements.v
Hi,
Here is an implementation of effective multivariate polynomials extracted from our formalization of [validsdp](https://sourcesup.renater.fr/validsdp/).
Note that this PR depends on [SsrMultinomials](https://github.com/math-comp/multinomials/commit/5b46e50983ee68dd1b6932e7e4a3bfc1113e7360) (so maybe some changes in Makefile or so would be necessary).
We tested this code with Coq 8.6 and MathComp 1.6.1.
Cc @CohenCyril @strub
Kind regards,
Erik and Pierre
> Add effective multivariate polynomials

- refinements/param.v
- refinements/refinements.v
Dear CoqEAL developers,
The development of the validsdp library led us implement this material, that could be useful for other users of CoqEAL.
Kind regards, Erik
> A few lemmas/tactics to ease proofs on lists, options, if-then-else expressions

- refinements/_CoqProject
- refinements/seqmx_complements.v
A few additional functions that were required for our development with erikmd.
Some might be too specific for inclusion into CoqEAL, feel free to choose.
P.S. : depends from previous PR about seqmx by erikmd.
> A few extra functions about seqmx.

- refinements/_CoqProject
just a minor bugfix extracted from PR CoqEAL/CoqEAL#12
> Remove duplicate line in refinements/_CoqProject

- .travis.yml
- refinements/seqmx.v
- theory/stronglydiscrete.v
This is backward compatible (i.e., still compiles with 8.7 and 8.8).
> Compile with coq 8.9 (beta)

- .travis.yml
- opam
- refinements/binnat.v
- refinements/binord.v
- refinements/binrat.v
- refinements/multipoly.v
This should be backward compatible. Let's wait for confirmation by the CI.
> Compile with Coq master and mathcomp.1.9.0

- coq-coqeal.opam
- refinements/multipoly.v
Not backward compatible. Updating the Opam file accordingly.
> Compile with mathcomp-multinomials 1.4

- .travis.yml
> Fix #28 (add opam update to CI)

- refinements/binrat.v
CoqEAL should now work on top od math-comp/math-comp#766
> Don't unfold too much rat definition

- .github/workflows/docker-action.yml
- refinements/binrat.v
Also add a few lemmas in passing.
> Use normalized operations in binrat

- README.md
- coq-coqeal.opam
- meta.yml
Followup to discussion in #45.
> repo name adjustments in metadata

- README.md
- meta.yml
I noticed that some relevant publications were missing from `meta.yml`. Added and updated `README.md`.
> add more related publications to meta.yml and README.md

- .github/workflows/docker-action.yml
- _CoqProject
- coq-coqeal.opam
- refinements/bareiss_eff.v
- refinements/binint.v
- refinements/binnat.v
- refinements/binord.v
- refinements/binrat.v
- refinements/boolF2.v
- refinements/examples/irred.v
- refinements/hpoly.v
- refinements/karatsuba.v
- refinements/multipoly.v
- refinements/param.v
- refinements/poly_div.v
- refinements/poly_op.v
- refinements/pos.v
- refinements/rational.v
- refinements/refinements.v
- refinements/seqmx.v
- refinements/seqmx_complements.v
- refinements/seqpoly.v
- refinements/trivial_seq.v
- theory/coherent.v
- theory/dvdring.v
- theory/fpmod.v
- theory/ssralg_ring_tac.v
- theory/stronglydiscrete.v
This drops support for Coq 8.13 and 8.14.
> [CI] Test Coq 8.17 and MC 1.16.0

- refinements/binrat.v
Adapt to coq-community/bignums#74
> Adapt to coq-community/bignums#74

- README.md
- coq-coqeal.opam
- meta.yml
- refinements/multipoly.v
Following the commit fc3a21d5aeddcc494e59f606260b240c0d61da34 on https://github.com/math-comp/multinomials
> Adapt the path of multinomials

- .github/workflows/docker-action.yml
- theory/polydvd.v
Adapt to https://github.com/math-comp/math-comp/pull/1223
> Adapt to https://github.com/math-comp/math-comp/pull/1223

- refinements/karatsuba.v
- theory/dvdring.v
https://github.com/math-comp/math-comp/pull/1256 changes the behavior of rewrite (seemingly because it generalizes some operations). This PR makes the necessary changes to keep compiling.
> adapt to MC#1256

- .github/workflows/docker-action.yml
- coq-coqeal.opam
- meta.yml
Update with Coq 8.20 and mathcomp 2.3.0
> [CI] Update with Coq 8.20 and mathcomp 2.3.0

- refinements/param.v
- refinements/rational.v
- refinements/seqmx.v
- refinements/seqpoly.v
Using https://github.com/LPCIC/coq-elpi/pull/758
> Use derive.param2.register

- refinements/binnat.v
- refinements/seqpoly.v
Adapt to https://github.com/math-comp/math-comp/pull/1343
> Adapt to https://github.com/math-comp/math-comp/pull/1343

- refinements/hpoly.v
- refinements/seqmx.v
- refinements/seqpoly.v
- theory/frobenius_form.v
Adapt to https://github.com/rocq-prover/rocq/pull/17876 and https://github.com/math-comp/math-comp/pull/1110
> Adapt to https://github.com/rocq-prover/rocq/pull/17876

- theory/fpmod.v
- theory/frobenius_form.v
- theory/kaplansky.v
- theory/similar.v
Adapt to https://github.com/rocq-prover/rocq/pull/20707
> Adapt to https://github.com/rocq-prover/rocq/pull/20707

- .github/workflows/docker-action.yml
- meta.yml
- refinements/multipoly.v
- refinements/param.v
Adapt to https://github.com/LPCIC/coq-elpi/pull/866
Also fix compilation on MC master following https://github.com/math-comp/multinomials/pull/101
> Adapt to https://github.com/LPCIC/coq-elpi/pull/866
